sonata_admin:
    title: Radenviro
    title_logo: /images/logo.png
    show_mosaic_button: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
